fm_elfinder:
    instances:
        form:
            editor: form
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg', 'image/jfif']
                        upload_deny: ['all']
                        upload_max_size: 10M
